#!/usr/bin/env bash
export DOTFILES=${1:-"$HOME/.dotfiles"}

# source environment variables from .env
set -a; source "${DOTFILES}/.env"; set +a

e='\033'
RESET="${e}[0m"
BOLD="${e}[1m"
CYAN="${e}[0;96m"
RED="${e}[0;91m"
YELLOW="${e}[0;93m"
GREEN="${e}[0;92m"

# Success reporter
info() {
    echo -e "${CYAN}${*}${RESET}"
}

# Error reporter
error() {
    echo -e "${RED}${*}${RESET}"
}

# Success reporter
success() {
    echo -e "${GREEN}${*}${RESET}"
}

# check if a command exists
_exists() {
	command -v "$1" > /dev/null 2>&1
}

_installed() {
	brew list "$1" &>/dev/null
}

# Extend $PATH without duplicates
_extend_path() {
    [[ -d "$1" ]] || return

    IN_PATH="echo '$PATH' | tr ":" '\n' | grep -qx '$1'"

    if ! eval "$IN_PATH" ; then
        export PATH="$1:$PATH"
    fi
}

# exit if not macOS
_is_macOS() {
    if [ "$(uname)" != "Darwin" ]; then
        return
    fi
}

_cmd_all(){
	local command="$1";
	shift
	local params_array=("$@");

	for param in "${params_array[@]}"
    do
        eval "$command $param"
    done
}