#!/usr/bin/env bash

# install node dependencies
brew install gpg gawk

# install asdf nodejs plugin
asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git

# install latests nodejs
asdf install nodejs latest

# activate latests nodejs globally
asdf global nodejs latest

# update npm
npm update -g npm