#!/usr/bin/env bash
ROOT_DIR="$( dirname "${BASH_SOURCE[0]:-$0}" )"
source "${ROOT_DIR}/_utils"

# only continue if on macOS
_is_macOS

# and install brew if it is not already installed
if ! _exists "brew"; then
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
	(echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> /Users/D052787/.zprofile
    	eval "$(/opt/homebrew/bin/brew shellenv)"
fi

if _exists "brew"; then
	brew bundle --file="$DOTFILES/Brewfile"
	[[ -f "$DOTFILES/local/Brewfile" ]] && brew bundle --file="$DOTFILES/local/Brewfile"
fi

# laod iTerm shell integrations
if ! _installed "iterm2"; then
	curl -L https://iterm2.com/shell_integration/install_shell_integration_and_utilities.sh | bash
fi

# complete mkcert
if _exists "mkcert"; then
	mkcert --install
fi

# cleanup
brew cleanup

