# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]

[plugins.oh-my-zsh]
github = "ohmyzsh/ohmyzsh"

[plugins.lib]
local = "~/.dotfiles/lib"

[plugins.spaceship]
github = 'spaceship-prompt/spaceship-prompt'

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.fzf-tb]
github = 'Aloxaf/fzf-tab'
apply = ["defer"]

[plugins.alias-tips]
github = 'djui/alias-tips'
apply = ["defer"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]
apply = ["defer"]

[plugins.zsh-autopair]
github = "hlissner/zsh-autopair"
apply = ["defer"]

[plugins.zsh-better-npm-completion]
github = "lukechilds/zsh-better-npm-completion"
apply = ["defer"]

[plugins.auto-notify]
github = "marzocchi/zsh-notify"
apply = ["defer"]

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-diff-so-fancy]
github = "z-shell/zsh-diff-so-fancy"
apply = ["defer", "PATH"]

[templates]
defer = '''
	{{ hooks?.pre | nl }}
		{% for file in files %}
			zsh-defer source "{{ file }}"
		{% endfor %}
	{{ hooks?.post | nl }}
'''